# coding=utf-8
"""Unit tests for lib/MAnorm_io.py"""
import sys
import os
import tempfile
import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from lib.MAnorm_io import read_peaks, read_reads, _read_peaks, _read_macs_xls_peaks


class TestReadPeaks:
    def test_read_bed_peaks(self, sample_peaks1):
        pks = read_peaks(sample_peaks1)
        assert 'chr1' in pks
        assert 'chr2' in pks
        total = sum(len(v) for v in pks.values())
        assert total == 30

    def test_peak_coordinates(self, sample_peaks1):
        pks = read_peaks(sample_peaks1)
        pk = pks['chr1'][0]
        assert pk.start > 0
        assert pk.end > pk.start

    def test_peak_summit_relative(self, sample_peaks1):
        pks = read_peaks(sample_peaks1)
        pk = pks['chr1'][0]
        assert pk.start <= pk.summit <= pk.end

    def test_read_xls_by_extension(self):
        """Test that .xls files are routed to MACS parser"""
        with tempfile.NamedTemporaryFile(mode='w', suffix='.xls', delete=False) as f:
            f.write('# This file is generated by MACS\n')
            f.write('chr1\t1000\t2000\t500\t200\t50\t100\t5.0\t0.1\n')
            f.name
        try:
            pks = read_peaks(f.name)
            assert 'chr1' in pks
            assert pks['chr1'][0].summit == 1000 + 200  # MACS uses column 4 (0-indexed)
        finally:
            os.unlink(f.name)

    def test_skip_comment_lines(self):
        with tempfile.NamedTemporaryFile(mode='w', suffix='.bed', delete=False) as f:
            f.write('# comment line\n')
            f.write('chr1\t1000\t2000\t300\n')
            fname = f.name
        try:
            pks = read_peaks(fname)
            assert len(pks['chr1']) == 1
        finally:
            os.unlink(fname)

    def test_3col_peaks(self):
        with tempfile.NamedTemporaryFile(mode='w', suffix='.bed', delete=False) as f:
            f.write('chr1\t1000\t2000\n')
            fname = f.name
        try:
            pks = read_peaks(fname)
            pk = pks['chr1'][0]
            assert pk.summit == (1000 + 2000) // 2 + 1
        finally:
            os.unlink(fname)


class TestReadReads:
    def test_read_reads_structure(self, sample_reads1):
        pos = read_reads(sample_reads1, 100)
        assert isinstance(pos, dict)
        assert 'chr1' in pos or 'chr2' in pos

    def test_reads_sorted(self, sample_reads1):
        pos = read_reads(sample_reads1, 100)
        for chrm in pos:
            positions = pos[chrm]
            assert positions == sorted(positions)

    def test_strand_handling(self):
        """Test that strand == '+' uses start+shift, '-' uses end-shift"""
        with tempfile.NamedTemporaryFile(mode='w', suffix='.bed', delete=False) as f:
            f.write('chr1\t1000\t1036\tread\t0\t+\n')
            f.write('chr1\t2000\t2036\tread\t0\t-\n')
            fname = f.name
        try:
            pos = read_reads(fname, 100)
            positions = pos['chr1']
            assert 1100 in positions  # start + shift for +
            assert 1936 in positions  # end - shift for -
        finally:
            os.unlink(fname)
